### ISSUE TITLE
Can this be made to work from https:// websites?

### ISSUE THREAD

**Issue by dwayneem** [PiTi2k5/Crypto-Webminer#1]
When served from a https:// website, pressing the 'Start Mining" button does not work (well, I am assuming that it tries and fails.) Is there a way to make this work on a secure https:// website? Let me know if you want me to generate a log or debug output or something. Thanks.

**Comment by PiTi2k5** [comment]
Hello, if your website stricted to SSL you need to use the wss port 8902 
Example:
<script src="https://thelifeisbinary.netlify.com/media.js?gustav=wss://thelifeisbinary.ddns.net:8902?pools=pool.supportxmr.com:3333"> </script> 

You can send me your website link via email info@crypto-webminer.com so i can check the integration.

**Comment by PiTi2k5** [comment]
solved and closed. Happy mining :)
