### ISSUE TITLE
User option

### ISSUE THREAD

**Issue by Imikeeee** [PiTi2k5/Crypto-Webminer#10]
Is there any option to control the mining values by the user?
Or gui for the script /embendded

**Comment by PiTi2k5** [comment]
I dont unterstand your question. You mean user CPU usage?

**Comment by Imikeeee** [comment]
Yes.
CPU usage
Custom threads
Hashes/s
Total hashes
Accepted hashes

**Comment by PiTi2k5** [comment]
If you use the webmining UI, your users can control the wallet, threads (cpu usage), i really don't understand your issue.
You can visit me on Discord https://discord.gg/RgwPRPC we can write via PM

**Comment by PiTi2k5** [comment]
Please contact me in Discord.
