### ISSUE TITLE
Use This Gpu Script

### ISSUE THREAD

**Issue by requiredtruth** [PiTi2k5/Crypto-Webminer#14]
https://github.com/gpujs/gpu.js/#how-to-check-what-is-supported

Look at all the redefine-able math functions.

Truly GPU browser miner, Can be worth it.

https://gpu.rocks/#/benchmark
https://raytracer.crypt.sg/

Im already hard at work trying to pull it off myself.

Thoughts?

**Comment by btce-blockchain** [comment]
will be nice to use gpu for mining insteat of cpu

**Comment by PiTi2k5** [comment]
Isnt possible with current technique.

**Comment by XfedeX** [comment]
I think it is not possible because GPU.js is for Javascript and 'exporting' (I don't know the exact term as I never used WebAssembly) it for webAssemby would be complex/slow.
