### ISSUE TITLE
SLOW LIKE HELL

### ISSUE THREAD

**Issue by korrykatti** [PiTi2k5/Crypto-Webminer#15]
hashrate is 7 why

**Comment by PiTi2k5** [comment]
Which device and pool / algo?

**Comment by korrykatti** [comment]
is there a option for custom pool ? i am on a 8 gb ram pc mining monero

**Comment by PiTi2k5** [comment]
Sure you can change https://github.com/PiTi2k5/Crypto-Webminer/blob/master/index.html#L17 or use custompoolsupport branch

**Comment by PiTi2k5** [comment]
But monero is only possible via auto algo switch pool with monero payout, because since last hardfork monero direct mining isnt possible anymore.

**Comment by korrykatti** [comment]
ok thanks
