### ISSUE TITLE
Doesn't work with ParsiCoin Block-v4

### ISSUE THREAD

**Issue by ParsiCoin** [PiTi2k5/Crypto-Webminer#2]
Hello , 
We are Using Your WebMiner at https://parsicoin.net/webminer , it was fine before we do block v4 hf but doesn't work anymore, here is the fork : https://github.com/ParsiCoin/pars-webminer
thanks for your help.

**Comment by PiTi2k5** [comment]
Hello,

please use always the newest script at https://github.com/PiTi2k5/Crypto-Webminer/blob/assets/media.js and try variant 2
I will take a look on parsicoin.

**Comment by PiTi2k5** [comment]
P.S ?algo=cn?variant=1 works :)

**Comment by ParsiCoin** [comment]
just updated media.js to latest version and it works ok , Thanks.
