### ISSUE TITLE
Intergration Help

### ISSUE THREAD

**Issue by TNT599** [PiTi2k5/Crypto-Webminer#21]
When I add the script it doesn't start mining to my wallet. Checked by opening pool website and not seeing a worker after a couple minutes. Help fixing please.

**Comment by TNT599** [comment]
I host the website on replit but it will move to heroku once the bugs are fixed. I just need it to automatically start mining. I have the script in between <body> and </body> I will contact on discord soon.

**Comment by PiTi2k5** [comment]
.
