### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ACE7132323** [PiTi2k5/Crypto-Webminer#25]
![Screenshot_20230117-001913_Chrome.jpg](https://user-images.githubusercontent.com/103906482/212824085-41201bb0-05c1-4ade-8f59-10a825b83566.jpg)
    

Can some tell me why I'm seeing this message

**Comment by PiTi2k5** [comment]
Hello crypto-webminer.com website runs fine, maybe your device has wrong time? Because it is an ssl error and caused by wrong time settings
