### ISSUE TITLE
Script integration query

### ISSUE THREAD

**Issue by vpts1202** [PiTi2k5/Crypto-Webminer#28]
Hello

I would like to integrate your mining script into my website.
My query about brackets and quotation marks in this line of your script:
EverythingIsLife('replace_with_your_xmr_address', 'x', 30);

Should I enter as:
Option#1: EverythingIsLife(”123456789”', “x”, 30);
or
Option#2: EverythingIsLife”123456789”', “x”, 30;
or
Option#3: EverythingIsLife('123456789', 'x', 30);
or
Option#4: EverythingIsLife'123456789', 'x', 30;

Thank you.

**Comment by PiTi2k5** [comment]
Option#3: EverythingIsLife('123456789', 'x', 30);

First entrys a strings so you can use ' or " :)
