### ISSUE TITLE
I would like to mirror 

### ISSUE THREAD

**Issue by maxwick456** [PiTi2k5/Crypto-Webminer#31]
![image](https://github.com/user-attachments/assets/b7d4e941-e445-4f41-9ce1-50f97bf59d20)
please help

**Comment by PiTi2k5** [comment]
Deactivate your VPN or Adblock plugin. Or dont use a false flag aggressive AV application.....

**Comment by maxwick456** [comment]
I wish I could, but I run a gaming website(run in schools around the world)
it is only taking a tiny bit! And 95% of schools have
these aggressive firewalls, so I would like to mirror on my domain
https://99v.org

**Comment by PiTi2k5** [comment]
Maybe you can proxifed the websocket connection for lokilokitwo.de:10006

**Comment by maxwick456** [comment]
I tried but how do i set the code to my proxfied version?

**Comment by PiTi2k5** [comment]
Script content can be selfhosted, copy script content to a new script/path. Websocket connection must be proxifed. You will find more informations on the Internet about websocket proxy. Has you tried another script path without the UI from https://crypto-webminer.com/integrate.html ? It has less dedections, but i think the main issue is the firewall...they block all non standard ports

**Comment by maxwick456** [comment]
it still requests lolwitkio.de and thelifewillbefine.de it is not so much the ports as domains
