### ISSUE TITLE
HTML version

### ISSUE THREAD

**Issue by Wesleymorais** [PiTi2k5/Crypto-Webminer#4]
Hi is possible build a HTML version to bem use the webgl technolgy?

I want test in a Xbox one S

**Comment by PiTi2k5** [comment]
Hello, webgl will not possible in near feature, sorry.

**Comment by Wesleymorais** [comment]
But is possible?
Because i'm not want mine Bitcoin, i want mine peercoin os more "easy" to
mine.

You can help me How to build a miner?

Em sáb, 9 de mar de 2019 14:13, PiTi <notifications@github.com> escreveu:
