### ISSUE TITLE
No accepted shares after hard fork

### ISSUE THREAD

**Issue by janfiedler** [PiTi2k5/Crypto-Webminer#5]
Hi, changed setting for cn/r algo, but no accepted shares now.
Even on your live demo.

It is only something on my side? Or any one else have same problem?

Thanks

**Comment by PiTi2k5** [comment]
Hello, i have tested the Github project single mining/custom pool support and live demo. It seems that supportxmr has an issue with static difficulty. All other pools works as expected with static diff for example wallet+5000

**Comment by PiTi2k5** [comment]
On supportxmr i needed a lot of total hashes for a single accepted share, but it shouldn't affect the payouts because higher diff shares gets better rewards. I will check it again later, maybe they work on their backend

**Comment by PiTi2k5** [comment]
I have change the default pool to another port, its working better now.
