### ISSUE TITLE
Difference between two js's

### ISSUE THREAD

**Issue by slayerulan** [PiTi2k5/Crypto-Webminer#6]
Hello,
Whats difference between these js files?

https://eth*****

https://easy*****

and i integrated easyhash to my website half hour ago, and still cant see my stats on moneroocean

**Comment by PiTi2k5** [comment]
On is new integration script with less AdBlocks and the other one is my webminer GUI script. Please send me an email with your website link, so i can checked the integration.

**Comment by slayerulan** [comment]
> Easyhash is new integration script with less AdBlocks and the other one is my webminer GUI script path. Please send me an email with your website link, so i can checked the integration.
> 
> [info@crypto-webminer.com](mailto:info@crypto-webminer.com) or discord via private message https://discord.gg/RgwPRPC

Thanks. Its working now, my website is huge so hope that websocket wouldnt crash :D

**Comment by PiTi2k5** [comment]
Issue closed. Happy mining.

**Comment by slayerulan** [comment]
Btw, if you change pool proxy user agent to xmr-node-proxy/0.0.3 when sending shares, Snipa22's pools (supportxmr, minexmr, moneroocean etc.) give lower difficulty = more profitability

Relevant commit: https://github.com/Snipa22/nodejs-pool/blob/76148a0f7da336bdd2f9bd8b1674a15265e5357c/lib/pool.js#L227
