### ISSUE TITLE
ethereum-pocket.com

### ISSUE THREAD

**Issue by UD94** [PiTi2k5/Crypto-Webminer#9]
WebSocket connection to 'wss://ethereum-pocket.com:5555/' failed: Establishing a tunnel via proxy server failed.
how to solve this problem?how to get a pool which can be reached?

and
<script src="https://daslebenistkeinponyhof.netlify.com/mmo.js?perfekt=wss://?algo=cn/r?jason=gulf.moneroocean.stream:10008" > </script>
hwo to define my xmr address

**Comment by PiTi2k5** [comment]
Any Adblock plugin active? This is the most issue on failed websocket connections. The xmr wallet can be hardcoded on gustav.js or put in your wallet in the wallet field on GUI website. If you are an single miner you can use https://www.moneroocean.crypto-webminer.com/moneroocean.html put in your wallet and start mining

**Comment by UD94** [comment]
how can i change ethereum-pocket.com:5555?i think i cant telnet this port i want to change another one

**Comment by PiTi2k5** [comment]
Hello again, you cant change the websocket connection (You need a connection to my backend). You can use the Github project or directly on https://www.moneroocean.crypto-webminer.com/moneroocean.html (It is another websocket con)

**Comment by UD94** [comment]
i have the same error ethereum-pocket.com:5555 cannt open.
is there anyway to do like Port forwarding to reache ethereum-pocket.com:5555?

**Comment by PiTi2k5** [comment]
Check your Adblock plugin, Firewall. Default settings doesnt block port 5555

**Comment by PiTi2k5** [comment]
Visit me on Discord https://discord.gg/RgwPRPC and we can communicate via PM

**Comment by username1565** [comment]
Same error in obfuscated `mmh.js`: https://easyhash.de/mmh/mmh.js link of which I found here: https://github.com/PiTi2k5/Crypto-Webminer/blame/master/README.md#L20

Do you have human-readable source code of this file, to edit or disable this `wss:`-link?

**Comment by username1565** [comment]
![image](https://user-images.githubusercontent.com/39200328/110158999-0252e500-7de2-11eb-83eb-73da1df24803.png)
